### ISSUE TITLE
Can't login to GUI

### ISSUE THREAD

**Issue by kafeinnet** [openmul/openmul#12]
Hi,

Just installed openmul for a lab but I can't manage to connect to the GUI.

All I get is this message when I enter the login/password : 
« Couln't connect due to the server error. Try again. »

Any clue on this ?

\fab

**Comment by openmul** [comment]
This is seen due to some configuration related issues in mysql. In Ubuntu 12.04 , you could try the following steps :

1. Clean-up packages  required by GUI
sudo apt-get remove --purge mysql-server mysql-client mysql-common
sudo apt-get autoremove
sudo rm -rf /var/lib/mysql
sudo apt-get remove  openjdk-7-jdk
sudo apt-get autoremove
sudo rm -fr /opt/tomcat

2. Reinstall (follow the steps in sequence)  :
sudo apt-get install mysql-server-5.5
cd <openmul>/
./build.sh -G

cd <openmul>/application/gui
$ sudo mysql -u root -p

mysql> source beem.sql
mysql> use beem;
mysql> exit

# Open a browser with address 
127.0.0.1:8080

# Login with following credentials (please note that commits have been made to change  the default user name/password so please update your code) - 
user: openmul
password : openmul

**Comment by openmul** [comment]
commit 3e5adf51dbc1b487460dddbf553b05679801198e
Author: Dipjyoti Saikia <dipjyoti.saikia@gmail.com>
Date:   Sat Feb 21 22:54:55 2015 +0900

    Issue#12 Made some changes to GUI login README and mysql configuration

**Comment by openmul** [comment]
commit a23dc246ded355e9062f720798c5793ff236512a
Author: Dipjyoti Saikia <dipjyoti.saikia@gmail.com>
Date:   Sat Feb 21 23:10:59 2015 +0900

    Issue#12 Updates to INSTALL.GUI for proper sequence of steps

**Comment by openmul** [comment]
Closing this as verified  to be working. For more info please check you can try our kickstarter VM at  http://www.openmul.org/openmul-vm.html
